name: Claymores
version: 2.0
api: [1.0.0]
author: Darunia18
description: When a player steps on a claymore, it explodes.
main: Darunia18\Claymores\Main
load: POSTWORLD
website: https://github.com/Darunia18/Claymores
